In [8]:
from sqlalchemy import create_engine
import random as rand
import pandas as pd

engine = create_engine('sqlite:///filez.db')

In [6]:
engine.dispose()

In [9]:
df = pd.read_sql('Select * from grades', engine, index_col = 'classes')
df

OperationalError: (sqlite3.OperationalError) no such table: grades [SQL: 'Select * from grades'] (Background on this error at: http://sqlalche.me/e/e3q8)